Loading rules from /opt/projects/by-ulid/01JJ9C1WHR0PNH43BQE1R0B3KS/logic/wg_rules
01JJ9C1Y7AT1YKK2R2P7WHBKBJ rule file: logic/wg_rules/Ticket_Price_Constraint.py
01JJ9C1YCMGESPW2WF2KWA0JHX rule file: logic/wg_rules/Passenger_Luggage_Weight_Sum.py

[34mVerifying rule: Ticket_Price_Constraint - 01JJ9C1Y7AT1YKK2R2P7WHBKBJ[0m
name 'Ticket' is not defined
Traceback (most recent call last):
  File "/opt/projects/by-ulid/01JJ9C1WHR0PNH43BQE1R0B3KS/logic/load_verify_rules.py", line 144, in verify_rules
    rule_module.init_rule()
  File "/opt/projects/by-ulid/01JJ9C1WHR0PNH43BQE1R0B3KS/logic/wg_rules/Ticket_Price_Constraint.py", line 6, in init_rule
    Rule.constraint(validate=Ticket,
                             ^^^^^^
NameError: name 'Ticket' is not defined
Loading rules from /opt/projects/by-ulid/01JJ9C1WHR0PNH43BQE1R0B3KS/logic/wg_rules
01JJ9C1Y7AT1YKK2R2P7WHBKBJ rule file: logic/wg_rules/Ticket_Price_Constraint.py
01JJ9C1YCMGESPW2WF2KWA0JHX rule file: logic/wg_rules/Passenger_Luggage_Weight_Sum.py
[32mLoading Rule Module Ticket_Price_Constraint 01JJ9C1Y7AT1YKK2R2P7WHBKBJ [0m
name 'Ticket' is not defined
Traceback (most recent call last):
  File "/opt/projects/by-ulid/01JJ9C1WHR0PNH43BQE1R0B3KS/logic/load_verify_rules.py", line 174, in load_active_rules
    rule_module.init_rule()
  File "/opt/projects/by-ulid/01JJ9C1WHR0PNH43BQE1R0B3KS/logic/wg_rules/Ticket_Price_Constraint.py", line 6, in init_rule
    Rule.constraint(validate=Ticket,
                             ^^^^^^
NameError: name 'Ticket' is not defined
[31mFailed to load active rule 01JJ9C1Y7AT1YKK2R2P7WHBKBJ Rule.constraint(validate=Ticket,
                as_condition=lambda row: row.price > 0,
                error_msg="Ticket price ({row.price}) must be greater than zero") [0m
[31mFailed to verify active rule code
Rule.constraint(validate=Ticket,
                as_condition=lambda row: row.price > 0,
                error_msg="Ticket price ({row.price}) must be greater than zero")
[33mNameError: name 'Ticket' is not defined[0m
01JJ9C1Y7AT1YKK2R2P7WHBKBJ rule file: logic/wg_rules/Ticket_Price_Constraint.py
01JJ9C1YCMGESPW2WF2KWA0JHX rule file: logic/wg_rules/Passenger_Luggage_Weight_Sum.py

[34mVerifying rule: Passenger_Luggage_Weight_Sum - 01JJ9C1YCMGESPW2WF2KWA0JHX[0m
Command '['python', '/opt/webgenai/database/manager.py', '-R', '01JJ9C1Y7AT1YKK2R2P7WHBKBJ', '--rule-error', "NameError: name 'Ticket' is not defined"]' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/projects/by-ulid/01JJ9C1WHR0PNH43BQE1R0B3KS/logic/load_verify_rules.py", line 174, in load_active_rules
    rule_module.init_rule()
  File "/opt/projects/by-ulid/01JJ9C1WHR0PNH43BQE1R0B3KS/logic/wg_rules/Ticket_Price_Constraint.py", line 6, in init_rule
    Rule.constraint(validate=Ticket,
                             ^^^^^^
NameError: name 'Ticket' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/projects/by-ulid/01JJ9C1WHR0PNH43BQE1R0B3KS/logic/load_verify_rules.py", line 209, in load_verify_rules
    load_active_rules(rule_code_dir, rules)
  File "/opt/projects/by-ulid/01JJ9C1WHR0PNH43BQE1R0B3KS/logic/load_verify_rules.py", line 178, in load_active_rules
    set_rule_error(rule["id"], f"{type(exc).__name__}: {exc}")
  File "/opt/projects/by-ulid/01JJ9C1WHR0PNH43BQE1R0B3KS/logic/load_verify_rules.py", line 60, in set_rule_error
    subprocess.check_output([
  File "/usr/local/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', '/opt/webgenai/database/manager.py', '-R', '01JJ9C1Y7AT1YKK2R2P7WHBKBJ', '--rule-error', "NameError: name 'Ticket' is not defined"]' returned non-zero exit status 1.
[31mFailed to load active exported rules: Command '['python', '/opt/webgenai/database/manager.py', '-R', '01JJ9C1Y7AT1YKK2R2P7WHBKBJ', '--rule-error', "NameError: name 'Ticket' is not defined"]' returned non-zero exit status 1.[0m

[32mActivated rule 01JJ9C1YCMGESPW2WF2KWA0JHX[0m
